%That is not why you first came here. You liar
clc
fprintf('T ')
pause(0.1)
fprintf('h ')
pause(0.1)
fprintf('a ')
pause(0.1)
fprintf('t ')
pause(0.1)
fprintf(' I')
pause(0.1)
fprintf(' s ')
pause(0.1)
fprintf(' N ')
pause(0.1)
fprintf('o ')
pause(0.1)
fprintf('t ')
pause(0.1)
fprintf(' W ')
pause(0.1)
fprintf('h ')
pause(0.1)
fprintf('y ')
pause(0.1)
fprintf(' Y ')
pause(0.1)
fprintf('o ')
pause(0.1)
fprintf('u ')
pause(0.1)
fprintf(' F ')
pause(0.1)
fprintf('i ')
pause(0.1)
fprintf('r ')
pause(0.1)
fprintf('s ')
pause(0.1)
fprintf('t ')
pause(0.1)
fprintf(' C ')
pause(0.1)
fprintf('a ')
pause(0.1)
fprintf('m ')
pause(0.1)
fprintf('e ')
pause(0.1)
fprintf(' H ')
pause(0.1)
fprintf('e ')
pause(0.1)
fprintf('r ')
pause(0.1)
fprintf('e. ')
pause(0.1)
fprintf('\nY ')
pause(0.1)
fprintf('O ')
pause(0.1)
fprintf('U ')
pause(0.1)
fprintf(' L ')
pause(0.1)
fprintf('I ')
pause(0.1)
fprintf('A ')
pause(0.1)
fprintf('R! \n')